### ISSUE TITLE
Full implementation/reproducibility of your paper

### ISSUE THREAD

**Issue by ksachdeva** [coolsunxu/BiTraP_NP#1]
Hi,

I read your paper yesterday and must mention that it is one of the better-written papers that I have read in the area of trajectory prediction. Thanks for this hard work.

Do you plan to release the rest of the code so that the results can be reproduced? Quite often the full code reveals more details than the paper.

Regards & thanks
Kapil

**Comment by coolsunxu** [comment]
I am not the author of this paper, I also read this paper accidentally, and then realized part of it myself, hahaha

**Comment by coolsunxu** [comment]
I am not the author of this paper, I also read this paper accidentally, and then realized part of it myself, hahaha

**Comment by coolsunxu** [comment]
> Hi,
> 
> I read your paper yesterday and must mention that it is one of the better-written papers that I have read in the area of trajectory prediction. Thanks for this hard work.
> 
> Do you plan to release the rest of the code so that the results can be reproduced? Quite often the full code reveals more details than the paper.
> 
> Regards & thanks
> Kapil

I am not the author of this paper, I also read this paper accidentally, and then realized part of it myself, hahaha

**Comment by ksachdeva** [comment]
Thanks @coolsunxu
